### PR TITLE
Add USCDI v3 to UI: SITE-3812

### PR DESCRIPTION
**Pull request by bgirishrao**

### CODE REVIEW

**Review by drbgfc — CHANGES_REQUESTED** [review]
USCDI v3 ts fiel is pointing to the wrong scenario repository. It's pointing to v2 instead of v3.

**Comment by drbgfc** [comment]
The issue:
  private senderGitHubUrl = 'https://api.github.com/repos/onc-healthit/2015-edition-cures-update-uscdi-v2-testdata/contents/Cures Update Svap Uscdiv2 Sender SUT Test Data';
  private receiverGitHubUrl = 'https://api.github.com/repos/onc-healthit/2015-edition-cures-update-uscdi-v2-testdata/contents/Cures Update Svap Uscdiv2 Receiver SUT Test Data';

**Review by drbgfc — COMMENTED** [review]
The rest of the code looks good

**Review by drbgfc — COMMENTED** [review]
Is this link valid?
private senderGitHubUrl = 'https://api.github.com/repos/onc-healthit/2015-edition-cures-update-uscdi-v3-testdata/contents/Cures Update Svap Uscdiv3 Sender SUT Test Data';

**Comment by austinmoody** [comment]
> Is this link valid? private senderGitHubUrl = 'https://api.github.com/repos/onc-healthit/2015-edition-cures-update-uscdi-v3-testdata/contents/Cures Update Svap Uscdiv3 Sender SUT Test Data';
> 
> I guess it's probably fine, I just don't know what the message "Not Found" implies? If ur happy with it, feel free to merge...

The URL's in code work for me if I copy them fully into the browser.  I think in comments here it breaks because of the spaces in the URL.  I've replaced those w/ %20 in the links below so we can see data is coming back.

- Sender [https://api.github.com/repos/onc-healthit/2015-edition-cures-update-uscdi-v3-testdata/contents/Cures Update Svap Uscdiv3 Sender SUT Test Data](https://api.github.com/repos/onc-healthit/2015-edition-cures-update-uscdi-v3-testdata/contents/Cures%20Update%20Svap%20Uscdiv3%20Sender%20SUT%20Test%20Data)
- Receiver: [https://api.github.com/repos/onc-healthit/2015-edition-cures-update-uscdi-v3-testdata/contents/Cures Update Svap Uscdiv3 Receiver SUT Test Data](https://api.github.com/repos/onc-healthit/2015-edition-cures-update-uscdi-v3-testdata/contents/Cures%20Update%20Svap%20Uscdiv3%20Receiver%20SUT%20Test%20Data)

The code must be handling the spaces because otherwise USCDIv2 wouldn't be working.

**Review by drbgfc — APPROVED** [review]

**Pull request merged**
